In [1]:
import cv2

In [2]:
# Read in an image from disk using imread method. 
# Note that 0 means the image can be loaded as grayscale.
img=cv2.imread('smallgray.png',0)

In [3]:
# The output is a 2D array representing the image
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
# A new image can be written to disk using imwrite
cv2.imwrite('newsmallgray.png', img)

True

In [5]:
# Slicing an array example
img[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [6]:
# : means all rows in this case
img[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [7]:
# Pluck a single value
img[2,4]

182

In [8]:
# Iterate by rows
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [9]:
# Iterate by cols (just transpose the array)
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [10]:
# Access as a flat list
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [11]:
# Access as a flat list after transpose
for i in img.T.flat:
    print(i)

187
198
209
158
125
134
104
255
255
121
255
97
143
147
182


In [20]:
# Remind ourself of the array shape and data
print("Array Shape:")
print(img.shape)
print("Array Data:")
print(img)

Array Shape:
(3, 5)
Array Data:
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [21]:
# Grab first two rows and first two columns using the slice notation
print(img[:2, :2])

[[187 158]
 [198 125]]


In [23]:
import numpy
# Stacking arrays
ims=numpy.hstack((img,img))

In [27]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [28]:
# Can also stack vertically of course
imsv=numpy.vstack((img,img))

In [29]:
print(imsv)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [34]:
# Splitting arrays
lst = numpy.hsplit(imsv, 5)

In [35]:
print(lst)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]
